version: "3.1"

services:

    openqa-single-instance:
        image: registry.opensuse.org/devel/openqa/containers/openqa-single-instance:latest
        container_name: openqa
        volumes:
          - ./iso:/var/lib/openqa/factory/iso
          - ./testplatform:/var/lib/openqa/tests/testplatform
        ports:
          - 1080:80
          - 1443:443
        restart: unless-stopped
        tty: true
